server:
  port: 8762

eureka:
  instance:
    hostname: eureka-2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5


spring:
  application:
    name: eurekaservice


