server:
  port: 8761

# unavailable-replicas: eurekas should have different hostname, or this issue would happen.
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-2:8762/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 5

spring:
  application:
    name: eurekaservice