apiVersion: apps/v1  # 1
kind: Deployment          # 2
metadata:
  name: http-server-2
spec:
  replicas: 2
  selector:
    matchLabels:          # 3
      app: http-server-2
  template:
    metadata:
      namespace: custom-ns-1
      name: pod-http-server-2
      labels:
        app: http-server-2
    spec:
      containers:
      - image: jianglichn/node-http-server-2:20191031.1210
        name: http-server-2
        livenessProbe:
          httpGet:
            path: /
            port: 3001
        ports:
        - containerPort: 3001
          protocol: TCP
