version: '2.1'

services:
  web:
    image: elkozmon/zoonavigator-web:0.6.1
    container_name: zoonavigator-web
    ports:
     - 18000:18000
    environment:
      WEB_HTTP_PORT: 18000
      API_HOST: "api"
      API_PORT: 19000
    depends_on:
     - api
    restart: always

  api:
    image: elkozmon/zoonavigator-api:0.6.1
    container_name: zoonavigator-api
    environment:
      API_HTTP_PORT: 19000
    restart: always
